name: zona_h
description: "A new Flutter project."

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  google_fonts: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
